AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "db/schema.rb"
    - "test/**/*.rb"
    - "spec/**/*.rb"
    - "config/environments/**/*.rb"
    - "lib/tasks/**/*.rake"

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/RescueException:
  Severity: fatal
  Enabled: true

Lint/UnusedBlockArgument:
  Severity: fatal
  Enabled: true

Metrics/LineLength:
  Severity: fatal
  Enabled: true

Metrics/MethodLength:
  Severity: convention
  CountComments: false
  Enabled: true
  Max: 10

Layout/AlignHash:
  Severity: fatal
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/AlignParameters:
  Severity: fatal
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Style/BracesAroundHashParameters:
  Severity: fatal
  Enabled: true

Naming/ConstantName:
  Severity: fatal
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Severity: fatal
  Enabled: true

Layout/ExtraSpacing:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/HashSyntax:
  Severity: fatal
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys

Layout/IndentationConsistency:
  Severity: fatal
  Enabled: true

Layout/IndentationWidth:
  Severity: fatal
  Enabled: true

Layout/IndentFirstHashElement:
  Severity: fatal
  Enabled: true
  EnforcedStyle: consistent

Style/InlineComment:
  Enabled: false

Style/LineEndConcatenation:
  Severity: fatal
  Enabled: true

Naming/MethodName:
  Severity: fatal
  Enabled: true

Style/MultilineTernaryOperator:
  Enabled: false

Style/NegatedIf:
  Severity: fatal
  Enabled: true

Style/Not:
  Severity: fatal
  Enabled: true

Style/RaiseArgs:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Severity: fatal
  Enabled: true

Style/StringLiterals:
  Severity: fatal
  Enabled: true
  EnforcedStyle: single_quotes

Layout/TrailingBlankLines:
  Severity: fatal
  Enabled: true

Layout/TrailingWhitespace:
  Severity: fatal
  Enabled: true

Naming/VariableName:
  Severity: fatal
  Enabled: true

Style/CollectionMethods:
  Severity: fatal
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Layout/DotPosition:
  Severity: fatal
  EnforcedStyle: leading

Lint/UselessAccessModifier:
  Description: 'Checks for useless access modifiers.'
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Description: 'Checks for trailing comma in array and hash literals.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-array-commas'
  Enabled: false

Style/TrailingCommaInArguments:
  Description: 'Checks for trailing comma in argument lists.'
  StyleGuide: '#no-trailing-params-comma'
  Enabled: false

Style/ClassAndModuleChildren:
  Severity: fatal
  Enabled: true
  EnforcedStyle: nested

Style/NumericLiterals:
  Enabled: false


