version: "3"
services:
    db:
        image: mysql:5.7
        container_name: same_lane_db
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - .env
        volumes:
            - ~/databases/same_lane:/var/lib/mysql/
        ports:
            - "3306:3306"
    web:
        build: .
        container_name: same_lane_web
        entrypoint: ["sh", "-c", "sleep infinity"]
#        command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        env_file:
            - .env
        tty: true
        stdin_open: true
        volumes:
            - //d_drive:/app
        ports:
            - "3000:3000"
        depends_on:
            - db
    webpacker:
        build: .
        container_name: same_lane_webpacker
        env_file:
            - .env
        command: ./bin/webpack-dev-server
        volumes:
            - //d_drive:/app
        ports:
            - "3035:3035"
